//! OpenClaw Orchestrator — Multi-agent planning + execution + verification.
//!
//! Inspired by the original Python OpenClaw system:
//! 1. **Planning**: LLM generates a structured plan
//! 2. **Execution**: Each step runs through the existing orchestrator
//! 3. **Verification**: Oracles validate the result

use std::path::PathBuf;
use std::sync::Arc;
use tracing::{info, warn};

use crate::provider::{
    LlmMessage, LlmProvider, MessageContent, ProviderOptions, Role,
};

use super::manager::MissionManager;
use super::models::{MissionSpec, MissionStatus};

// ─── Plan Step ──────────────────────────────────────────────────

/// A step in the mission plan generated by the Planner agent.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PlanStep {
    pub id: usize,
    pub summary: String,
    #[serde(default)]
    pub tool_hint: Option<String>,
}

/// Full plan with rationale and steps.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct MissionPlan {
    pub rationale: String,
    pub steps: Vec<PlanStep>,
    /// Estimated complexity (1-10).
    #[serde(default)]
    pub complexity: u8,
}

// ─── Planner Agent ──────────────────────────────────────────────

const PLANNER_SYSTEM_PROMPT: &str = r#"You are the OwnStack Mission Planner.

Given a mission description and its technical spec, generate a detailed execution plan.

Return a JSON object with:
{
  "rationale": "Brief explanation of your approach",
  "steps": [
    {"id": 1, "summary": "Step description", "tool_hint": "optional tool name"},
    ...
  ],
  "complexity": 1-10
}

Rules:
- Each step should be atomic and independently verifiable
- Order steps logically (read before write, test after code)
- Keep steps actionable and specific
- Include verification steps (e.g., "Run cargo test")
- Return ONLY the JSON, no markdown"#;

/// Generate a mission plan from a prompt and spec.
pub async fn generate_plan(
    provider: &Arc<dyn LlmProvider>,
    description: &str,
    spec: &MissionSpec,
) -> Result<MissionPlan, String> {
    let input = format!(
        "MISSION DESCRIPTION: {description}\n\n\
         MISSION SPEC: {}",
        serde_json::to_string_pretty(spec).unwrap_or_default()
    );

    let messages = vec![
        LlmMessage {
            role: Role::System,
            content: MessageContent::Text(PLANNER_SYSTEM_PROMPT.to_string()),
            tool_calls: None,
            tool_call_id: None,
        },
        LlmMessage {
            role: Role::User,
            content: MessageContent::Text(input),
            tool_calls: None,
            tool_call_id: None,
        },
    ];

    let response = provider
        .complete(messages, None, ProviderOptions::default())
        .await
        .map_err(|e| format!("Planner LLM call failed: {e}"))?;

    let json_str =
        super::compiler::extract_json(&response.content.unwrap_or_default());

    serde_json::from_str::<MissionPlan>(&json_str).map_err(|e| {
        warn!("OpenClaw planner JSON parse failed: {e}");
        format!("Plan parsing failed: {e}")
    })
}

// ─── Oracle (Verifier) ──────────────────────────────────────────

/// Run verification oracles in the workspace.
pub fn run_oracle(workspace: &PathBuf, oracle_cmd: &str) -> OracleResult {
    use std::process::Command;

    info!("OpenClaw Oracle: running '{oracle_cmd}' in {:?}", workspace);

    let output = Command::new(if cfg!(windows) { "cmd" } else { "sh" })
        .args(if cfg!(windows) {
            vec!["/C", oracle_cmd]
        } else {
            vec!["-c", oracle_cmd]
        })
        .current_dir(workspace)
        .output();

    match output {
        Ok(out) => {
            let stdout = String::from_utf8_lossy(&out.stdout).to_string();
            let stderr = String::from_utf8_lossy(&out.stderr).to_string();
            let passed = out.status.success();

            OracleResult {
                command: oracle_cmd.to_string(),
                passed,
                stdout,
                stderr,
                exit_code: out.status.code().unwrap_or(-1),
            }
        }
        Err(e) => OracleResult {
            command: oracle_cmd.to_string(),
            passed: false,
            stdout: String::new(),
            stderr: format!("Failed to execute oracle: {e}"),
            exit_code: -1,
        },
    }
}

#[derive(Debug, Clone)]
pub struct OracleResult {
    pub command: String,
    pub passed: bool,
    pub stdout: String,
    pub stderr: String,
    pub exit_code: i32,
}

// ─── OpenClaw Orchestrator ──────────────────────────────────────

/// The top-level orchestrator that manages the full mission lifecycle:
/// Planning → Execution → Verification.
pub struct OpenClawOrchestrator {
    provider: Arc<dyn LlmProvider>,
    workspace: PathBuf,
}

impl OpenClawOrchestrator {
    pub fn new(provider: Arc<dyn LlmProvider>, workspace: PathBuf) -> Self {
        Self {
            provider,
            workspace,
        }
    }

    /// Run the full mission lifecycle.
    ///
    /// The caller provides a `MissionManager` and an `execute_step` callback
    /// that integrates with the existing orchestrator loop.
    pub async fn run_mission<F, Fut>(
        &self,
        mission_manager: &mut MissionManager,
        mission_id: &str,
        execute_step: F,
    ) -> Result<(), String>
    where
        F: Fn(String) -> Fut,
        Fut: std::future::Future<Output = Result<String, String>>,
    {
        // Clone data we need before mutating the manager
        let (description, spec, oracles) = {
            let mission = mission_manager
                .get_mission(mission_id)
                .ok_or_else(|| format!("Mission '{mission_id}' not found"))?;
            let desc = mission.description.clone();
            let sp = mission.spec.clone().unwrap_or_default();
            let orc = sp.oracles.clone();
            (desc, sp, orc)
        };

        // 1. PLANNING
        mission_manager.update_status(
            mission_id,
            MissionStatus::Planning,
            "Generating execution plan...",
        );

        let plan = generate_plan(&self.provider, &description, &spec).await?;

        mission_manager.add_log(
            mission_id,
            &format!(
                "Plan: {} ({} steps, complexity {})",
                plan.rationale,
                plan.steps.len(),
                plan.complexity
            ),
        );

        mission_manager.create_checkpoint(mission_id, "Before execution", None);

        // 2. EXECUTION
        mission_manager.update_status(
            mission_id,
            MissionStatus::Running,
            &format!("Executing {} steps...", plan.steps.len()),
        );

        for step in &plan.steps {
            mission_manager
                .add_log(mission_id, &format!("Step {}: {}", step.id, step.summary));

            let prompt = format!(
                "Context: {}\nStep {}/{}: {}",
                plan.rationale,
                step.id,
                plan.steps.len(),
                step.summary
            );

            match execute_step(prompt).await {
                Ok(result) => {
                    let truncated = &result[..result.len().min(200)];
                    mission_manager.add_log(
                        mission_id,
                        &format!("Step {} completed: {}", step.id, truncated),
                    );
                }
                Err(e) => {
                    mission_manager.add_log(
                        mission_id,
                        &format!("Step {} failed: {e}", step.id),
                    );
                    mission_manager.update_status(
                        mission_id,
                        MissionStatus::Failed,
                        &format!("Step {} failed: {e}", step.id),
                    );
                    return Err(format!("Step {} failed: {e}", step.id));
                }
            }

            mission_manager.create_checkpoint(
                mission_id,
                &format!("After step {}", step.id),
                None,
            );
        }

        // 3. VERIFICATION
        if !oracles.is_empty() {
            mission_manager.update_status(
                mission_id,
                MissionStatus::Verifying,
                "Running verification oracles...",
            );

            let mut all_passed = true;
            for oracle_cmd in &oracles {
                let result = run_oracle(&self.workspace, oracle_cmd);
                mission_manager.add_log(
                    mission_id,
                    &format!(
                        "Oracle '{}': {} (exit {})",
                        oracle_cmd,
                        if result.passed { "PASSED" } else { "FAILED" },
                        result.exit_code
                    ),
                );
                if !result.passed {
                    all_passed = false;
                }
            }

            if all_passed {
                mission_manager.update_status(
                    mission_id,
                    MissionStatus::Completed,
                    "All oracles passed. Mission completed successfully.",
                );
            } else {
                mission_manager.update_status(
                    mission_id,
                    MissionStatus::Failed,
                    "Verification failed. Check oracle results.",
                );
                return Err("Verification oracles failed".to_string());
            }
        } else {
            mission_manager.update_status(
                mission_id,
                MissionStatus::NeedsReview,
                "Execution complete. No oracles defined — manual review required.",
            );
        }

        Ok(())
    }
}

// ─── Tests ──────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_plan_step_serialization() {
        let plan = MissionPlan {
            rationale: "Fix the login bug".to_string(),
            steps: vec![
                PlanStep {
                    id: 1,
                    summary: "Read auth.rs".to_string(),
                    tool_hint: Some("read_file".to_string()),
                },
                PlanStep {
                    id: 2,
                    summary: "Fix validation".to_string(),
                    tool_hint: None,
                },
            ],
            complexity: 5,
        };

        let json = serde_json::to_string(&plan).unwrap();
        let parsed: MissionPlan = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.steps.len(), 2);
        assert_eq!(parsed.complexity, 5);
    }

    #[test]
    fn test_oracle_runs_echo() {
        let dir = tempfile::tempdir().unwrap();
        let result = run_oracle(&dir.path().to_path_buf(), "echo hello");
        assert!(result.passed);
        assert!(result.stdout.contains("hello"));
    }

    #[test]
    fn test_oracle_detects_failure() {
        let dir = tempfile::tempdir().unwrap();
        let result = run_oracle(
            &dir.path().to_path_buf(),
            if cfg!(windows) {
                "cmd /C exit 1"
            } else {
                "false"
            },
        );
        assert!(!result.passed);
    }
}
