from __future__ import annotations
from enum import Enum
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field
import uuid
import datetime

class MissionStatus(str, Enum):
    PENDING = "pending"
    PLANNING = "planning"
    RUNNING = "running"
    VERIFYING = "verifying"
    NEEDS_REVIEW = "needs_review"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"

class WorkerType(str, Enum):
    CLAUDE_CODE = "claude_code"
    OWNSTACK_AGENT = "ownstack_agent"
    OPENCLAW_NATIVE = "openclaw_native"

class MissionMode(str, Enum):
    A1_STATIC_READ = "A1_static_read"   # Zero execution, pure parsing
    A2_SAFE_TOOLING = "A2_safe_tooling" # Non-destructive tools (LSP, linters)
    B_DYNAMIC_EXEC = "B_dynamic_exec"   # Code execution / tests in sandbox
    C_HYPOTHETICAL = "C_hypothetical"   # Planned but not currently possible

class Permission(str, Enum):
    FS_READ = "fs_read"
    FS_WRITE = "fs_write"
    NETWORK = "network"
    CONTAINER_EXEC = "container_exec"

class ExecutionStrategy(str, Enum):
    EPHEMERAL_BRANCH = "ephemeral_branch"
    PATCH_LOG = "patch_log"
    DRY_RUN = "dry_run"
    DIRECT_APPLY = "direct_apply" # Only for authorized dogfooding

class MissionSpec(BaseModel):
    """The formal contract generated by the Prompt Compiler."""
    mode: MissionMode
    strategy: Optional[ExecutionStrategy] = ExecutionStrategy.DRY_RUN
    objectives: List[str]
    scope: List[str] # Directories/Files
    permissions: List[Permission]
    oracles: List[str] # e.g. ["npm test", "pytest"]
    stop_conditions: List[str]
    output_format: List[str]
    budget_tokens: Optional[int] = None
    preflight_checks: Dict[str, bool] = {} # Detected by system before start

class MissionEvent(BaseModel):
    timestamp: datetime.datetime = Field(default_factory=datetime.datetime.now)
    type: str  # log, diff, screenshot, status_change
    message: str
    data: Optional[Dict[str, Any]] = None

class MissionCheckpoint(BaseModel):
    """SOTA Phase 76: Mission State Checkpoint."""
    id: str = Field(default_factory=lambda: f"ckpt_{uuid.uuid4().hex[:8]}")
    timestamp: datetime.datetime = Field(default_factory=datetime.datetime.now)
    description: str
    mission_status: MissionStatus
    # Snapshot of key metrics or state
    events_count: int
    metadata_snapshot: Dict[str, Any]

class Mission(BaseModel):
    id: str = Field(default_factory=lambda: f"miss_{uuid.uuid4().hex[:8]}")
    title: str
    description: str
    status: MissionStatus = MissionStatus.PENDING
    worker_type: WorkerType = WorkerType.CLAUDE_CODE
    project_path: str
    created_at: datetime.datetime = Field(default_factory=datetime.datetime.now)
    updated_at: datetime.datetime = Field(default_factory=datetime.datetime.now)
    events: List[MissionEvent] = []
    # SOTA Phase 76: Checkpoints
    checkpoints: List[MissionCheckpoint] = []
    metadata: Dict[str, Any] = {}
    spec: Optional[MissionSpec] = None # The compiled contract
    
    def add_event(self, event_type: str, message: str, data: Optional[Dict[str, Any]] = None):
        self.events.append(MissionEvent(type=event_type, message=message, data=data))
        self.updated_at = datetime.datetime.now()

    def set_spec(self, spec: MissionSpec):
        """Attach a compiled spec to the mission."""
        self.spec = spec
        # Auto-update description/title if generic? 
        # For now, just attach.
